package ru.softstone.kotime.presentation

const val SPLASH_SCREEN = "SPLASH_SCREEN"
const val TIMER_SCREEN = "TIMER_SCREEN"
const val ACTIONS_SCREEN = "ACTIONS_SCREEN"
const val EDIT_ACTION_SCREEN = "EDIT_ACTION_SCREEN"
const val CATEGORIES_SCREEN = "CATEGORIES_SCREEN"
const val CATEGORY_SCREEN = "CATEGORY_SCREEN"
const val SUGGESTION_SCREEN = "SUGGESTION_SCREEN"
const val STAT_SCREEN = "STAT_SCREEN"
const val ERROR_SCREEN = "ERROR_SCREEN"
const val CONTRIBUTE_SCREEN = "CONTRIBUTE_SCREEN"
